project:
  type: website
  output-dir: docs

website:
  title: "Ahmed Samir"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ahmedsamirio
      - icon: linkedin
        href: https://www.linkedin.com/in/ahmedsamir95/
format:
  html:
    theme: cosmo
    css: styles.css



